insert into facilities (type, id, name, location) values ('INDOOR', 1, 'Nlounge', 'Talmadge');
insert into facilities (type, id, name, location) values ('OUTDOOR', 2, 'Dynabox', 'Anhalt');
insert into facilities (type, id, name, location) values ('INDOOR', 3, 'Oodoo', 'Bultman');
insert into facilities (type, id, name, location) values ('INDOOR', 4, 'Realbridge', 'Buell');
insert into facilities (type, id, name, location) values ('INDOOR', 5, 'Tagopia', 'Di Loreto');
insert into facilities (type, id, name, location) values ('OUTDOOR', 6, 'Lajo', 'Stang');
insert into facilities (type, id, name, location) values ('INDOOR', 7, 'Skivee', 'Forest Dale');
insert into facilities (type, id, name, location) values ('OUTDOOR', 8, 'Youtags', 'Messerschmidt');
insert into facilities (type, id, name, location) values ('OUTDOOR', 9, 'Gigabox', 'Ruskin');
insert into facilities (type, id, name, location) values ('INDOOR', 10, 'Vimibo', 'Ridgeview');
insert into facilities (type, id, name, location) values ('INDOOR', 11, 'Thoughtstorm', 'Sunfield');
insert into facilities (type, id, name, location) values ('INDOOR', 12, 'Zoomcast', 'Lighthouse Bay');
insert into facilities (type, id, name, location) values ('INDOOR', 13, 'Voolith', 'Comanche');
insert into facilities (type, id, name, location) values ('OUTDOOR', 14, 'Livepath', 'Arizona');
insert into facilities (type, id, name, location) values ('INDOOR', 15, 'Dynazzy', 'Express');
insert into facilities (type, id, name, location) values ('INDOOR', 16, 'Oyondu', 'Eastwood');
insert into facilities (type, id, name, location) values ('OUTDOOR', 17, 'Gabtune', 'Sullivan');
insert into facilities (type, id, name, location) values ('INDOOR', 18, 'Youspan', 'Sunfield');
insert into facilities (type, id, name, location) values ('OUTDOOR', 19, 'Meevee', 'Lake View');
insert into facilities (type, id, name, location) values ('INDOOR', 20, 'Ntag', 'Autumn Leaf');
insert into facilities (type, id, name, location) values ('OUTDOOR', 21, 'Agimba', 'Randy');
insert into facilities (type, id, name, location) values ('INDOOR', 22, 'Livetube', 'Merrick');
insert into facilities (type, id, name, location) values ('OUTDOOR', 23, 'Vimbio', 'Miller');
insert into facilities (type, id, name, location) values ('OUTDOOR', 24, 'Dabjam', 'Eastwood');
insert into facilities (type, id, name, location) values ('OUTDOOR', 25, 'Eire', 'Hanover');
insert into facilities (type, id, name, location) values ('INDOOR', 26, 'Skaboo', 'Warner');
insert into facilities (type, id, name, location) values ('OUTDOOR', 27, 'Rhynoodle', 'Dennis');
insert into facilities (type, id, name, location) values ('INDOOR', 28, 'Twitterworks', 'Johnson');
insert into facilities (type, id, name, location) values ('OUTDOOR', 29, 'Feedfire', 'Claremont');
insert into facilities (type, id, name, location) values ('INDOOR', 30, 'Rhyzio', 'Valley Edge');